version: '3.1'
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot
    ports:
      - 5432:5432
      
  web:
    container_name: rest_demo
    image: rest_demo
    environment:
        - db_url=jdbc:postgresql://postgres-db:5432/iot
        - db_user=postgres
        - db_password=postgres
    env_file:
        - postgres.env
    ports:
      - 8888:8080
    depends_on:
      - postgres-db
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
# Volumes
#volumes:
#  ./sql:

# Networks to be created to facilitate communication between containers
#networks:
#  demoNet:
